[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  CI = "false"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
